tasks:
  - name: terraform
    before: |
      source ./bin/install_terraform_cli
      source ./bin/set_tf_alias
      source ./bin/generate_tfrc_credentials 
      cp /workspace/terraform-beginner-bootcamp-2023/terraform.tfvars.example /workspace/terraform-beginner-bootcamp-2023/terraform.tfvars
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli
      source ./bin/set_tf_alias 
  - name: http-server
    before: |
      npm install --global http-server
    command:
      http-server
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform